export const jointThemePicker: string;
export const jointThemeModern: string;
export const jointApp: string;
export const appTitle: string;
export const inspectorContainer: string;
export const jointWidget: string;
export const jointToolbar: string;
export const toolbarContainer: string;
export const appBody: string;
